categories:
  weapons:
    img-path: 'textures/items/iron_sword'
    text: "§6Weapons"
  armors:
    img-url: 'https://image.ibb.co/cRO3h8/skin_2013052515355615141both.png'
    text: "§bArmors"

items:
  # itemId : itemMeta : optionName : price per item count : url/path : imgpath
  # Example : 276:0:Sword:2500:path:textures/items/diamond_sword
  weapons:
    - "268:0:Wooden Sword:100:path:textures/items/wood_sword"
    - "272:0:Stone Sword:200:path:textures/items/stone_sword"
    - "283:0:Golden Sword:300:path:textures/items/gold_sword"
    - "267:0:Iron Sword:400:path:textures/items/iron_sword"
    - "276:0:Diamond Sword:500:path:textures/items/diamond_sword"
    - "261:0:Bow:600:path:textures/items/bow_standby"
    - "262:0:Arrow:1000:path:textures/items/arrow"
  armors:
    - "310:0:§bDiamond Helmet:250:path:textures/items/diamond_helmet"
    - "311:0:§bDiamond Chestplate:350:path:textures/items/diamond_chestplate"
    - "312:0:§bDiamond Leggings:450:path:textures/items/diamond_leggings"
    - "313:0:§bDiamond Boots:550:path:textures/items/diamond_boots"